

platform :ios, '7.0'
pod 'AFNetworking', '~> 2.2.3'
pod 'SDWebImage', '~> 3.5.4'
pod 'MWPhotoBrowser', '~> 1.4.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'pop', '~> 1.0.6'
pod 'JDStatusBarNotification', '~> 1.4.8'




